- mandelbulber2/src/audio_track.cpp
Fixes Clang warning
'delete' applied to a pointer that was allocated with 'new';
did you mean 'delete[]'? [-Wmismatched-new-delete]
> Fix mismatched delete[]

- mandelbulber2/src/primitives.cpp
- mandelbulber2/src/primitives.h
This is needed to avoid memory leaks of memory allocated with "new"
in the constructor.
> Add explicit destructor for cPrimitives

- mandelbulber2/src/file_image.cpp
- mandelbulber2/src/files.cpp
- mandelbulber2/src/netrender.cpp
In netrender.cpp, also check that reconnectTimer is not NULL before
stopping the timer, similar to how clientSocket is treated.
See also #167.
> Clean up some memory leaks

- mandelbulber2/src/common_math.h
- mandelbulber2/src/render_worker.hpp
This was spotted by UBsan:
runtime error: load of value 190, which is not a valid value for type 'bool'
The field has never been used, so just remove it.
> Remove unused sVectorsAround member notBlack

- README.md
- mandelbulber2/src/animation_flight.cpp
- mandelbulber2/src/interface.cpp
- mandelbulber2/src/render_window.hpp
- mandelbulber2/src/render_window_slots.cpp
- mandelbulber2/src/rendered_image_widget.cpp
- mandelbulber2/src/rendered_image_widget.hpp
Hi all
I'm using Mandelbulber for some hours now, and I realized that I missed some keyboard shortcuts to navigate more quickly in 3D world.
Here is a proposal of some shortcuts (have a look to readme.md for description).
I tried them for some time and I'm happy with that. Hope it'll be your case too.
The advantage using arrows than W/S/A/D is that it works the same independently of the keyboard layout (I'm actualy using an AZERTY layout, and W/S/A/D doesn't feel intuitive).
> Add keyboard shortcuts for keyboard navigation

- mandelbulber2/src/animation_keyframes.cpp
> Fix #174: "The animation has already been rendered completely." when rendering keyframes based animation

- mandelbulber2/src/rendered_image_widget.cpp
Okay, I'm really not sure about the code here. It **seems** to work, but I'm sure there are some cases it doesn't. I didn't find them.
This is a quick'n dirty fix to allow you to see what I needed while exploring fractales in SBS cross eyed mode (the mode I use the more for exploring).
Thanks and sorry about this dirty code ! But, you get the idea.
> Display double crosshair in render window when stereoscopic SBS mode enabled

- mandelbulber2/src/fractal_formulas.cpp
Without the brackets, temp1 might be used uninitialized.
It looks like this was the intention, especially when comparing this with lines 8248-8263, but do check that this is sane.
> Add missing brackets after if-statement

- mandelbulber2/src/audio_track_collection.cpp
- mandelbulber2/src/audio_track_collection.h
- mandelbulber2/src/clew-cl.hpp
- mandelbulber2/src/statistics.h
Note that cAudioTrackCollection::{Add,Remove}Parameters can be made
const since the parameters are added/removed to the cParameterContainer
class passed as argument.
> Add const to member functions

- mandelbulber2/src/render_worker.cpp
Fixes compilation warnings for both gcc and clang:
warning: unused variable 'rayBranch' [-Wunused-variable]
> Remove unused variable

- mandelbulber2/src/files.cpp
If the path was not found, the same path was tried again and again.
Fix this by trying the alternate paths instead.
Add newlines to the printouts to not print all paths on the line.
The changes makes it possible to run the example file
mandelbulber2/deploy/share/mandelbulber2/examples/Robert Pancoast
collection - license Creative Commons (CC-BY 4.0)/icoastahedron.fract
even if the repo isn't checked out to D:/GIT/mandelbulber2.
> Bugfix FilePathHelper

- mandelbulber2/qt/dock_navigation.cpp
Silences a clang warning:
../qt/dock_navigation.cpp:215:53: warning: unused parameter 'enabled' [-Wunused-parameter]
void cDockNavigation::EnableOpenCLModeComboBox(bool enabled) const
^
1 warning generated.
> Mark unused argument

- mandelbulber2/src/cast.hpp
Seems it's never used but let's fix it anyway.
> Fix assert in CastIntToSize

- mandelbulber2/src/cimage.hpp
The removed returns can never be executed. These were introduced
in 1a028db4b.
> Remove consecutive returns

- mandelbulber2/qt/preferences_dialog.cpp
Preselect 1st GPU device in the preferences when open for the first time, so a GPU device is selected when enabling OpenCL
> Preselect 1st GPU device in preferences when open for the first time

- .travis.yml
It will install  opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev packages and compile mandelbulber-opencl.pro. All test will not use OpenCL.
> Trying to compile OpenCL version with travisCI

- mandelbulber2/qt/image_save_dialog.ui
- mandelbulber2/qt/preferences_dialog.ui
- mandelbulber2/src/cimage.cpp
- mandelbulber2/src/cimage.hpp
- mandelbulber2/src/file_image.cpp
- mandelbulber2/src/file_image.hpp
- mandelbulber2/src/initparameters.cpp
- mandelbulber2/src/netrender_server.hpp
- mandelbulber2/src/render_image.cpp
- mandelbulber2/src/render_job.cpp
- mandelbulber2/src/render_worker.cpp
hey,
so finally managed to implement the world normal pass with the help of my colleague.
https://github.com/buddhi1980/mandelbulber2/issues/576
also fixed a small cosometic change with the existing screenscace normal pass, as I suggested here: https://github.com/buddhi1980/mandelbulber2/issues/576#issuecomment-501719851.
only implemented for CPU, guess OpenCL would unfortantely be a bit too tricky for us.
build and tested in Windows with MSCV 2017
would be awesome if you could merge that
thx
> implemented world normal pass, fixed screenspace normal pass

- mandelbulber2/deploy/linux/com.github.buddhi1980.mandelbulber2.metainfo.xml
Add metainfo for mandelbulber.
This is a metadata of an app, useful when it is package and display in some kind of app store like Flathub.
https://flathub.org/apps/details/com.github.buddhi1980.mandelbulber2
Also, are you interest to be the co-owner of Flathub repo of Mandelbulber?
https://github.com/flathub/com.github.buddhi1980.mandelbulber2
> Add metainfo for mandelbulber.

- Dockerfile
Resolves #857
This PR has the following changes in the Dockerfile.
- container user now has name `mandelbulber` and can run `mandelbulber2` from $(id).
- Change to filetype in COPY step so it can successfuly resolve archive from previous stage.
<!-- If you are adding an example, make sure it only refers to files in
$SHARED_DIR, which are the files under
mandelbulber2/deploy/share/mandelbulber2, see
mandelbulber2/deploy/share/mandelbulber2/data/mandelbulber_1.21_defaults.fract
for an example (e.g. file_background)
> Fix Docker build (#857)

- mandelbulber2/qmake/common.pri
By injecting -I/usr/include/gsl, `#include <algorithm>` starts to mean "use ms-gsl's algorithm" rather than the C++ stdlib one. But all of the includes for ms-gsl here are properly namespaced, e.g. <gsl/foo.h>, so we can drop the explicit -I*.
Bug: https://bugs.gentoo.org/834692
> qmake: fix build when ms-gsl is installed
