- .appveyor.yml
- .travis.yml
- README.md
- this fixes c++-11 issues
- also new ci for windows (does not build yet)
TODO: @buddhi1980 setup appveyor analogue to travis and modify badge link in README
> ci build update

- mandelbulber2/src/animation_flight.cpp
- mandelbulber2/src/animation_keyframes.cpp
- mandelbulber2/src/command_line_interface.cpp
- mandelbulber2/src/command_line_interface.hpp
- mandelbulber2/src/system.cpp
- mandelbulber2/src/system.hpp
This is useful for shell scripting.
> Add CLI option "silentOption" to silently exit without user prompt.

- mandelbulber2/src/algebra.hpp
> Optimize isNaN performance

- .gitignore
What are your thoughts on ignoring standard artifacts?
> Add .gitignore to project folder

- mandelbulber2/src/algebra.hpp
> StructuredCVector3

- README.md
Added links to mandelbulber2 Arch Linux AUR packages
> Links to Arch Linux AUR packages

- mandelbulber2/src/nine_fractals.cpp
Perhaps it would be possible to add a build with clang on Linux in Travis?
> Don't try to count withoutDEFunction

- mandelbulber2/src/algebra.cpp
- mandelbulber2/src/algebra.hpp
- mandelbulber2/src/animation_frames.hpp
- mandelbulber2/src/camera_target.hpp
- mandelbulber2/src/color_palette.hpp
- mandelbulber2/src/fractal_list.hpp
- mandelbulber2/src/keyframes.hpp
- mandelbulber2/src/one_parameter.cpp
- mandelbulber2/src/one_parameter.hpp
- mandelbulber2/src/texture.cpp
- mandelbulber2/src/texture.hpp
Add const to some member functions that can be const. There are a few more classes where it could be added but I figured I'd send a somewhat small PR first to see if you are interested in it.
> Some const correctness

- mandelbulber2/src/cimage.cpp
- mandelbulber2/src/cimage.hpp
- mandelbulber2/src/command_line_interface.cpp
- mandelbulber2/src/command_line_interface.hpp
- mandelbulber2/src/headless.cpp
- mandelbulber2/src/headless.h
- mandelbulber2/src/morph.cpp
- mandelbulber2/src/morph.hpp
- mandelbulber2/src/scheduler.cpp
- mandelbulber2/src/scheduler.hpp
- mandelbulber2/src/settings.cpp
- mandelbulber2/src/settings.hpp
- mandelbulber2/src/statistics.h
- mandelbulber2/src/stereo.cpp
- mandelbulber2/src/stereo.h
- mandelbulber2/src/system.hpp
Now in one commit. ;)
This was the last ones I (or rather cppcheck) could find.
> Add more consts

- .travis.yml
Test if traviscl will build the program
> Change gcc to version 6.2

- mandelbulber2/qt/dock_queue.h
- mandelbulber2/src/old_settings.hpp
> Remove self-includes

- .appveyor.yml
Pending Build Checks:
https://ci.appveyor.com/project/mancoast/mandelbulber2-0c0m0/build/1.0.101
> MSBuild Solution for Appveyor

- .travis.yml
TravisCl configured to use make-package.sh and install script. This test if application is ready for deployment. The program is run from /usr/bin for --test
> Travis installer test

- mandelbulber2/src/algebra.cpp
Make sure all elements are properly set.
> Bugfix CRotationMatrix44::Null

- mandelbulber2/qt/audio_selector.cpp
- mandelbulber2/qt/image_save_dialog.cpp
- mandelbulber2/qt/material_manager_view.cpp
- mandelbulber2/qt/system_tray.cpp
- mandelbulber2/qt/system_tray.hpp
Address sanitizer reported a couple of places where memory wasn't freed when the program was closed. This change adds delete to a few destructors to free the memory when the windows are closed.
> Free memory in destructors

- mandelbulber2/src/camera_target.hpp
- mandelbulber2/src/cimage.hpp
- mandelbulber2/src/clew-cl.hpp
- mandelbulber2/src/command_line_interface.cpp
- mandelbulber2/src/command_line_interface.hpp
- mandelbulber2/src/morph.cpp
- mandelbulber2/src/morph.hpp
- mandelbulber2/src/parameters.cpp
- mandelbulber2/src/parameters.hpp
- mandelbulber2/src/progress_text.cpp
- mandelbulber2/src/progress_text.hpp
Change some const functions to be static instead. In theory, it can lead to faster code (since no "this"-pointer is needed), but in practice, I doubt it is noticeable. It doesn't hurt though.
> Make some functions static

- mandelbulber2/src/test.cpp
This improves readability by printing each file on a line of its own,
instead of printing to the same line.
> Add newline to test case printouts

- mandelbulber2/formula/opencl/fold_box_mod1.cl
- mandelbulber2/src/fractal_formulas.cpp
Make sure colorAdd is initialized before using it.
> Bugfix FoldBoxMod1Iteration

- README.md
> fix some small grammar issues

- mandelbulber2/qt/dock_effects.ui
> Add tooltip for MC chromatic aberration

- README.md
> fix small grammatical error

- mandelbulber2/src/main.cpp
- mandelbulber2/src/netrender.cpp
- mandelbulber2/src/netrender.hpp
- mandelbulber2/src/netrender_client.cpp
- mandelbulber2/src/netrender_client.hpp
- mandelbulber2/src/netrender_server.cpp
- mandelbulber2/src/netrender_server.hpp
- mandelbulber2/src/netrender_transport.cpp
- mandelbulber2/src/netrender_transport.hpp
- mandelbulber2/src/render_image.cpp
- mandelbulber2/src/test.cpp
the netrender code is now basically stable again (did some tests with reconnection stopping and starting of server and clients and rendering).
Also the overall structure should be stable now (some code needs to be ported to client / server). But these should be testable / incremental changes.
IMHO this is ready to merge, @buddhi1980 what do you think?
> Netrender refactor

- contrib/vfx_tools/houdini/scripts/python/hou_mandelbulber.py
hey,
sorry small bug fix again. but this one is quite important so even though its just a little change i want it merged asap.
thx
btw. the tool works quite well in general. helps me a lot dealing with animation. use it constantly.
only problem is when dealing with very deep zoom anims. because Houdini parameter precision is limited and at some point it cuts of decimals that are crucial for the anim to work.
no way around this iI fear.
> fixed bug when exporting and no flight keyframes were present

- Dockerfile
- adds Dockerfile for archlinux based opencl builds
> add archlinux docker build with opencl support

- README.md
- add Archlinux mandelbulber2-opencl-git to README
> add Archlinux mandelbulber2-opencl-git

- mandelbulber2/cmake/CMakeLists.txt
- mandelbulber2/qmake/common.pri
Resolves #900
This is my fix for it, I tested both build paths and everything seems to work great.
> Upgrade build files for linking with OpenEXR 3
